name: Despliegue en multi stage

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Relleno
        run: echo "Este step no hace nada realmente"
  staging:
    environment: staging
    runs-on: ubuntu-latest
    needs: build 
    name: Job de staging
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4
      - name: Hacer despliegue en ${{ vars.ETAPA }}
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: bash deploy.sh ${{ vars.ETAPA }} | tee resultado_${{ vars.ETAPA }}.txt
      - name: Guardar resultado
        id: results-staging
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: |
          echo "${{ vars.ETAPA }}=$(cat resultado_${{ vars.ETAPA }}.txt| grep -i Deployment)" >> "$GITHUB_OUTPUT"
    outputs:
        log-staging: ${{ steps.results-staging.outputs.staging }}
  production:
    name: Job de prod
    environment: "production"
    runs-on: ubuntu-latest
    needs: [build, staging ]
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4
      - name: Hacer despliegue en ${{ vars.etapa }}
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: bash deploy.sh ${{ vars.etapa }} | tee resultado_${{ vars.ETAPA }}.txt
      - name: Guardar resultado
        id: results-production
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: |
          echo "${{ vars.ETAPA }}=$(cat resultado_${{ vars.ETAPA }}.txt | grep -i Deployment") >> "$GITHUB_OUTPUT"
    outputs:
        log-production: ${{ steps.results-production.outputs.production }}
  upload_artifacts:
    name: Generar evidencias
    runs-on: ubuntu-latest
    needs: [build, staging, production]
    steps:
      - name: Recolectar evidencias
        run: |
          echo ${{ needs.staging.outputs.log-staging }} > resultados.txt
          echo ${{ needs.production.outputs.log-production }} >> resultados.txt
          cat resultados.txt
      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          path: resultados.txt
