name: Postgress

on:
  push:
    branches:
      - "main"
env:
  PPASS: ${{ secrets.postgress_password }}
jobs:
  Job_unico:
    name: Lab de Postgress
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v4
      - name: Preparar cache python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: Desplegar contenedor Docker
        run: |
          docker run --name postgres-db \
          -e POSTGRES_PASSWORD=${{ env.PPASS }} \
          -p 5432:5432 \
          -e POSTGRES_USER=user \
          -e POSTGRES_DB=testdb \
          -d postgres:latest
      - name: Cache de la imagen Docker
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: ${{ runner.arch }}
      - name: Instalar dependencias python
        run: pip install psycopg2
      - name: Validar la conectividad al contenedor
        env:
          password: ${{ env.PPASS }}
        working-directory: "D1-06-Database-Service-Containers/Desafio 1/"
        run: python test_db_connection.py

